version: "3.3"
services:

  bot:
    build:
      context: .
      dockerfile: telegram_bot/Dockerfile
    container_name: bot
    env_file:
      - .env
    restart: always
    tty: True
    working_dir: /telegram_bot

  api:
    build:
      context: .
      dockerfile: api_flask_rest/Dockerfile
    container_name: api
    env_file:
      - .env
    ports:
      - "5001:5001"
    restart: unless-stopped
    tty: True
    working_dir: /api_flask_rest